version: '3'
services:
  
  gateway:
    build:
      dockerfile: dockerfile
      context: ./Gateway
    environment:
    # network of account_manager service
      - account_manager=account_manager:50051
    volumes:
      - statics:/src/statics:rw
    depends_on:
      - account_manager
    networks:
      - microservices
    restart: always
    entrypoint: ["sh", "./entrypoint.dev.sh"]

  nginx:
    build:
      dockerfile: ./dockerfile.nginx
      context: ./Gateway
    depends_on:
      - gateway
    environment:
      # dns and port of gateway
      - GATEWAY_PORT=8000
      - GATEWAY_HOST=gateway
    ports:
      - 8080:80
    volumes:
      - statics:/statics:rw
    restart: always


  
  account_manager:
    build:
      dockerfile: dockerfile
      context: ./Account-Manager
    environment:
      - POSTGRES_HOST=account_manager_db
    depends_on:
      - account_manager_db
    entrypoint: ["sh", "./entrypoint.dev.sh"]
    restart: always
    networks:
      - microservices
      - db
  
  account_manager_db:
    image: postgres:alpine
    env_file:
      - ./Account-Manager/config/postgresql.dev.env
    networks:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    restart: always
 

networks:
    microservices:
    db: